### ISSUE TITLE
Dropdown menu crashes when alt-tabbing back to standalone sample

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#122]
If you run the standalone sample app, then open a dropdown menu, select another window, then alt-tab back to the sample app, you get this:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: FocusManager must not be null
	at org.jetbrains.jewel.DropdownKt$DropdownMenu$3.invoke-ZmokQxo(Dropdown.kt:201)
	at org.jetbrains.jewel.DropdownKt$DropdownMenu$3.invoke(Dropdown.kt:195)
	at androidx.compose.ui.input.key.KeyInputNode.onKeyEvent-ZmokQxo(KeyInputModifier.kt:80)
	at androidx.compose.ui.focus.FocusOwnerImpl.dispatchKeyEvent-ZmokQxo(FocusOwnerImpl.kt:200)
	at androidx.compose.ui.platform.SkiaBasedOwner.sendKeyEvent-ZmokQxo(SkiaBasedOwner.skiko.kt:211)
	at androidx.compose.ui.ComposeScene.sendKeyEvent-ZmokQxo(ComposeScene.skiko.kt:735)
	at androidx.compose.ui.awt.ComposeBridge$onKeyEvent$1.invoke(ComposeBridge.desktop.kt:257)
	at androidx.compose.ui.awt.ComposeBridge$onKeyEvent$1.invoke(ComposeBridge.desktop.kt:253)
	...
```

Note: this probably happens with dropdown links as well. Can't check it right now.

**Comment by fscarponi** [comment]
Can't reproduce anymore
