### ISSUE TITLE
`Typography` APIs don't appears to be usable due to "Can't add together different TextUnits"

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/jewel#316]
When trying Jewel in our IntelliJ plugin here: https://github.com/slackhq/slack-gradle-plugin/pull/772

we're finding that using `Typography` APIs like `Typography.h0TextStyle()` don't seem to work out of the box because they rely on combining with default styles that may be `Unspecified`.

```
java.lang.IllegalStateException: Can't add together different TextUnits. Got Unspecified and Sp
	at org.jetbrains.jewel.ui.component.TypographyKt.plus-NB67dxo(Typography.kt:76)
	at org.jetbrains.jewel.ui.component.Typography.h0TextStyle(Typography.kt:36)
	at com.slack.sgp.intellij.projectgen.ProjectGenUiKt$ProjectGen$5$1.invoke(ProjectGenUi.kt:95)
	at com.slack.sgp.intellij.projectgen.ProjectGenUiKt$ProjectGen$5$1.invoke(ProjectGenUi.kt:80)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at com.slack.sgp.intellij.projectgen.ProjectGenUiKt.ProjectGen(ProjectGenUi.kt:80)
	at com.slack.sgp.intellij.projectgen.ProjectGenWindow$DialogContent$lambda$5$lambda$4$$inlined$ui$1.Content(Ui.kt:99)
	at com.slack.circuit.foundation.CircuitContentKt.CircuitContent(CircuitContent.kt:144)
	at com.slack.circuit.foundation.CircuitContentKt.CircuitContent(CircuitContent.kt:109)
	at com.slack.circuit.foundation.CircuitContentKt$CircuitContent$3.invoke(CircuitContent.kt:88)
	at com.slack.circuit.foundation.CircuitContentKt$CircuitContent$3.invoke(CircuitContent.kt:87)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at com.slack.circuit.foundation.CircuitContentKt.CircuitContent(CircuitContent.kt:87)
	at com.slack.circuit.foundation.CircuitContentKt.CircuitContent(CircuitContent.kt:31)
	at com.slack.sgp.intellij.projectgen.ProjectGenWindow$DialogContent$1.invoke(ProjectGenWindow.kt:82)
	at com.slack.sgp.intellij.projectgen.ProjectGenWindow$DialogContent$1.invoke(ProjectGenWindow.kt:82)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1$1.invoke(SwingBridgeTheme.kt:34)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1$1.invoke(SwingBridgeTheme.kt:33)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1.invoke(SwingBridgeTheme.kt:30)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1.invoke(SwingBridgeTheme.kt:29)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2$1.invoke(JewelTheme.kt:197)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2$1.invoke(JewelTheme.kt:196)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2.invoke(JewelTheme.kt:192)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2.invoke(JewelTheme.kt:191)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:70)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt$JewelTheme$1.invoke(JewelTheme.kt:64)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt$JewelTheme$1.invoke(JewelTheme.kt:63)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:63)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt.BaseJewelTheme(JewelTheme.kt:191)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt.SwingBridgeTheme(SwingBridgeTheme.kt:25)
	at com.slack.sgp.intellij.projectgen.SlackDesktopThemeKt.SlackDesktopTheme(SlackDesktopTheme.kt:25)
	at com.slack.sgp.intellij.projectgen.ProjectGenWindow.DialogContent(ProjectGenWindow.kt:82)
	at com.slack.sgp.intellij.projectgen.ProjectGenWindow$createCenterPanel$1.invoke(ProjectGenWindow.kt:48)
	at com.slack.sgp.intellij.projectgen.ProjectGenWindow$createCenterPanel$1.invoke(ProjectGenWindow.kt:47)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at org.jetbrains.jewel.bridge.actionSystem.ProvideDataKt.ComponentDataProviderBridge(ProvideData.kt:37)
	at org.jetbrains.jewel.bridge.JewelComposePanelKt$JewelComposePanel$1$1$1$1.invoke(JewelComposePanel.kt:20)
	at org.jetbrains.jewel.bridge.JewelComposePanelKt$JewelComposePanel$1$1$1$1.invoke(JewelComposePanel.kt:19)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at org.jetbrains.jewel.bridge.JewelComposePanelKt$JewelComposePanel$1$1$1.invoke(JewelComposePanel.kt:19)
	at org.jetbrains.jewel.bridge.JewelComposePanelKt$JewelComposePanel$1$1$1.invoke(JewelComposePanel.kt:18)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1$1.invoke(SwingBridgeTheme.kt:34)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1$1.invoke(SwingBridgeTheme.kt:33)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1.invoke(SwingBridgeTheme.kt:30)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt$SwingBridgeTheme$1.invoke(SwingBridgeTheme.kt:29)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2$1.invoke(JewelTheme.kt:197)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2$1.invoke(JewelTheme.kt:196)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2.invoke(JewelTheme.kt:192)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2.invoke(JewelTheme.kt:191)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:70)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt$JewelTheme$1.invoke(JewelTheme.kt:64)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt$JewelTheme$1.invoke(JewelTheme.kt:63)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:63)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt.BaseJewelTheme(JewelTheme.kt:191)
	at org.jetbrains.jewel.bridge.theme.SwingBridgeThemeKt.SwingBridgeTheme(SwingBridgeTheme.kt:25)
	at org.jetbrains.jewel.bridge.JewelComposePanelKt$JewelComposePanel$1$1.invoke(JewelComposePanel.kt:18)
	at org.jetbrains.jewel.bridge.JewelComposePanelKt$JewelComposePanel$1$1.invoke(JewelComposePanel.kt:17)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.scene.ComposeContainer$setContent$1$1.invoke(ComposeContainer.desktop.kt:243)
	at androidx.compose.ui.scene.ComposeContainer$setContent$1$1.invoke(ComposeContainer.desktop.kt:242)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.scene.ComposeContainer_desktopKt.ProvideContainerCompositionLocals(ComposeContainer.desktop.kt:347)

```

**Comment by rock3r** [comment]
As far as I remember, we never init those as unspecified. They are hard coded sp values. Are you adding unspecified to them? Or what is the context in which an unspecified gets thrown in?

The more info you can provide, the better. Thanks Zac :)

**Comment by ZacSweers** [comment]
We're not specifying/overriding them anywhere. Is the repro project not enough?

**Comment by rock3r** [comment]
Ah i missed that! Sorry, it's late and I'm on the phone :) Will take a look as soon as I can, hopefully on Monday

**Comment by rock3r** [comment]
@ZacSweers I've looked into this, I can't repro the crash either in your PR branch nor in the Jewel IDE sample (when using the Typography API). What IDE version are you using? What theme? Is New UI enabled? And what OS are you on? And which version of Jewel?

**Comment by rock3r** [comment]
FWIW, in the bridge, this is how text styles (including the default, "Label.font") are retrieved:

```kotlin
public fun retrieveTextStyle(
    key: String,
    color: Color = Color.Unspecified,
    lineHeight: TextUnit = TextUnit.Unspecified,
    bold: Boolean = false,
    fontStyle: FontStyle = FontStyle.Normal,
    size: TextUnit = TextUnit.Unspecified,
): TextStyle {
    val lafFont = UIManager.getFont(key) ?: keyNotFound(key, "Font")
    val jbFont = JBFont.create(lafFont, false)

    val derivedFont = jbFont.let { if (bold) it.asBold() else it.asPlain() }
        .let { if (fontStyle == FontStyle.Italic) it.asItalic() else it }

    return TextStyle(
        color = color,
        fontSize = size.takeOrElse { derivedFont.size.sp / UISettingsUtils.getInstance().currentIdeScale },
        fontWeight = if (bold) FontWeight.Bold else FontWeight.Normal,
        fontStyle = fontStyle,
        fontFamily = derivedFont.asComposeFontFamily(),
        // TODO textDecoration might be defined in the AWT theme
        lineHeight = lineHeight,
    )
}
```

The way the default font is read, `size` is always `Undefined`, and thus the size of the default font is set to `derivedFont.size.sp / UISettingsUtils.getInstance().currentIdeScale`, which is always in `Sp`.

**Comment by ZacSweers** [comment]
Here's a video walk through. Sorry I should've pointed out explicitly that you need to uncomment those usages in the PR. Here's a video demo walking through


https://github.com/JetBrains/jewel/assets/1361086/20d05acc-4040-43cf-ade6-22c5d728448e

**Comment by ZacSweers** [comment]
Specific written steps. Sorry again for not including this upfront

- Checkout the repo at the linked branch
- Open ProjectGenUi.kt
- Uncomment any of the `Typography.*` usages, such as `Typography.h0TextStyle()`
- Run the plugin with `./gradlew :skate-plugin:runIde`
- IDE runs in `2023.2.1`
- File > New > Slack Subproject
- <error>

**Comment by rock3r** [comment]
Thanks Zac, hopefully I have all I need now :) I'll try to repro again tomorrow
