### ISSUE TITLE
DecoratedWindow produces JRE / JBR related error in Release Distributable

### ISSUE THREAD

**Issue by Tre5et** [JetBrains/jewel#323]
In a Release build of my Compose Multiplatform project for desktop (using task `:runReleaseDistributable` or `:createReleaseDistributable` and executing the produced `.exe` file, both using the IDE and `./gradlew` from the command line) the following error is produced:

```
java.lang.ClassNotFoundException: com.jetbrains.JBR$Metadata
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(Unknown Source)
	at java.base/com.jetbrains.internal.JBRApi.init(Unknown Source)
	at java.base/com.jetbrains.bootstrap.JBRApiBootstrap.bootstrap(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.jetbrains.JBR.<clinit>(JBR.java:66)
	at org.jetbrains.jewel.window.DecoratedWindowKt.DecoratedWindow(DecoratedWindow.kt:63)
	at net.treset.treelauncher.ComposableSingletons$MainKt$lambda-2$1$1.invoke(main.kt:2063)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at org.jetbrains.jewel.intui.standalone.theme.IntUiThemeKt$IntUiTheme$2$1.invoke(IntUiTheme.kt:1223)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at org.jetbrains.jewel.intui.standalone.theme.IntUiThemeKt$IntUiTheme$2.invoke(IntUiTheme.kt:1220)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2$1.invoke(JewelTheme.kt:2197)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2.invoke(JewelTheme.kt:2192)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:70)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt$JewelTheme$1.invoke(JewelTheme.kt:2064)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:63)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt.BaseJewelTheme(JewelTheme.kt:191)
	at org.jetbrains.jewel.intui.standalone.theme.IntUiThemeKt.IntUiTheme(IntUiTheme.kt:215)
	at net.treset.treelauncher.ComposableSingletons$MainKt$lambda-2$1.invoke(main.kt:2059)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:2117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:1233)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:1223)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.animation.core.InfiniteAnimationPolicyKt.invokeComposable(InfiniteAnimationPolicy.kt:3033)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3303)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3236)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1071)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "main" java.lang.IllegalStateException: DecoratedWindow can only be used on JetBrainsRuntime(JBR) platform, please check the document https://github.com/JetBrains/jewel#int-ui-standalone-theme
	at org.jetbrains.jewel.window.DecoratedWindowKt.DecoratedWindow(DecoratedWindow.kt:65)
	at net.treset.treelauncher.ComposableSingletons$MainKt$lambda-2$1$1.invoke(main.kt:2063)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at org.jetbrains.jewel.intui.standalone.theme.IntUiThemeKt$IntUiTheme$2$1.invoke(IntUiTheme.kt:1223)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at org.jetbrains.jewel.intui.standalone.theme.IntUiThemeKt$IntUiTheme$2.invoke(IntUiTheme.kt:1220)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2$1.invoke(JewelTheme.kt:2197)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt$BaseJewelTheme$2.invoke(JewelTheme.kt:2192)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:70)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt$JewelTheme$1.invoke(JewelTheme.kt:2064)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at org.jetbrains.jewel.foundation.theme.JewelThemeKt.JewelTheme(JewelTheme.kt:63)
	at org.jetbrains.jewel.ui.theme.JewelThemeKt.BaseJewelTheme(JewelTheme.kt:191)
	at org.jetbrains.jewel.intui.standalone.theme.IntUiThemeKt.IntUiTheme(IntUiTheme.kt:215)
	at net.treset.treelauncher.ComposableSingletons$MainKt$lambda-2$1.invoke(main.kt:2059)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:2117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:1233)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:1223)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.animation.core.InfiniteAnimationPolicyKt.invokeComposable(InfiniteAnimationPolicy.kt:3033)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3303)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3236)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1071)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Failed to launch JVM
```

The following tasks work as expected:

- `:run`
- `:runRelease`
- `:createDistributable`

I have made sure:

- The project and gradle are configured to use JBR 17.0.9 installed through IntelliJ
- `JAVA_HOME` environment variable is set to the JBR instance
- `./gradlew --version` shows the correct JBR version
- Kotlin version: 1.9.10
- Compose version: 1.6.1
- Jewel Version: 0.15.2

**Comment by devkanro** [comment]
It seems still a JBR config issue, can you provide your `./gradlew --version` output, and `java -version`

**Comment by devkanro** [comment]
@Tre5et 
Do you create release by `./gradlew runReleaseDistributable`

**Comment by Tre5et** [comment]
This seems to have been a ProGuard configuration issue.

Adding the line
```
-keep class com.jetbrains.** { *; }
```
to my ProGuard config fixed this error.

Event thought this is an issue that isn't specific to Jewel, but should affect any library relying on the JBR, it may be worth adding this to the standalone section of the ReadMe.

**Comment by rock3r** [comment]
Thanks for the follow-up and the fix info, @Tre5et! We don't explicitly support ProGuard, so when you use it your mileage may vary a lot. As mentioned in #319, you can refer to https://github.com/romainguy/kotlin-explorer/blob/main/compose-desktop.pro as an example of ProGuard rules to use.

However, I'd like to stress once again, we don't support using ProGuard right now, and don't plan to at the very least in the short/medium term. I will make a note to this effect in the readme, even if I have little hope people will actually read it 🙃
