### ISSUE TITLE
UnsatisfiedLinkError from TypefaceFontProviderWithFallbackKt in 0.23.0 using jewel-int-ui-standalone-241

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/jewel#564]
Repro: https://github.com/slackhq/slack-gradle-plugin/pull/937

Run the `main()` function in `ProjectGenPlayground.kt`.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt._nMakeAsFallbackProvider()'
	at org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt._nMakeAsFallbackProvider(Native Method)
	at org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt.access$_nMakeAsFallbackProvider(TypefaceFontProviderWithFallback.kt:1)
	at org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallback.<init>(TypefaceFontProviderWithFallback.kt:16)
	at androidx.compose.ui.text.platform.FontCache.<init>(PlatformFont.skiko.kt:201)
	at androidx.compose.ui.text.platform.FontLoader.<init>(PlatformFont.skiko.kt:177)
	at androidx.compose.ui.node.RootNodeOwner$OwnerImpl.<init>(RootNodeOwner.skiko.kt:339)
	at androidx.compose.ui.node.RootNodeOwner.<init>(RootNodeOwner.skiko.kt:149)
	at androidx.compose.ui.node.RootNodeOwner.<init>(RootNodeOwner.skiko.kt)
	at androidx.compose.ui.scene.CanvasLayersComposeSceneImpl.<init>(CanvasLayersComposeScene.skiko.kt:114)
	at androidx.compose.ui.scene.CanvasLayersComposeSceneImpl.<init>(CanvasLayersComposeScene.skiko.kt)
	at androidx.compose.ui.scene.CanvasLayersComposeScene_skikoKt.CanvasLayersComposeScene-3tKcejY(CanvasLayersComposeScene.skiko.kt:93)
	at androidx.compose.ui.scene.CanvasLayersComposeScene_skikoKt.CanvasLayersComposeScene-3tKcejY$default(CanvasLayersComposeScene.skiko.kt:85)
	at androidx.compose.ui.scene.ComposeContainer.createComposeScene(ComposeContainer.desktop.kt:358)
	at androidx.compose.ui.scene.ComposeContainer.access$createComposeScene(ComposeContainer.desktop.kt:84)
	at androidx.compose.ui.scene.ComposeContainer$mediator$3.invoke(ComposeContainer.desktop.kt:142)
	at androidx.compose.ui.scene.ComposeContainer$mediator$3.invoke(ComposeContainer.desktop.kt:142)
	at androidx.compose.ui.scene.ComposeSceneMediator$scene$2.invoke(ComposeSceneMediator.desktop.kt:291)
	at androidx.compose.ui.scene.ComposeSceneMediator$scene$2.invoke(ComposeSceneMediator.desktop.kt:291)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.ui.scene.ComposeSceneMediator.getScene(ComposeSceneMediator.desktop.kt:291)
	at androidx.compose.ui.scene.ComposeSceneMediator.setCompositionLocalContext(ComposeSceneMediator.desktop.kt:295)
	at androidx.compose.ui.scene.ComposeContainer.setCompositionLocalContext(ComposeContainer.desktop.kt:170)
	at androidx.compose.ui.awt.ComposeWindowPanel.setCompositionLocalContext(ComposeWindowPanel.desktop.kt:76)
	at androidx.compose.ui.awt.ComposeWindow.setCompositionLocalContext(ComposeWindow.desktop.kt:114)
	at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:411)
	at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:408)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2$1.invoke(AwtWindow.desktop.kt:70)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2$1.invoke(AwtWindow.desktop.kt:69)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1364)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:992)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1013)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1142)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by rock3r** [comment]
Thanks Zac, will look into it today. Did not come up in release testing, sorry 😞

**Comment by rock3r** [comment]
Can confirm this does not repro in our samples. Will check your repo.

**Comment by rock3r** [comment]
I can repro in your project, however, the issue is not a Jewel bug. You're using Compose 1.6.11, while you should be matching Jewel's version, 1.7.0-alpha03.

This patch fixes the issue:

```
Subject: [PATCH] Update CMP to match required version
---
Index: gradle/libs.versions.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/gradle/libs.versions.toml b/gradle/libs.versions.toml
--- a/gradle/libs.versions.toml	(revision 8ebe35dad8fa8e5775a00ee1bd903dea5f6fe292)
+++ b/gradle/libs.versions.toml	(date 1724829069119)
@@ -4,7 +4,7 @@
 anvil = "2.5.0-beta11"
 bugsnagGradle = "8.1.0"
 circuit = "0.23.1"
-compose-jb = "1.6.11"
+compose-jb = "1.7.0-alpha03"
 coroutines = "1.8.1"
 dependencyAnalysisPlugin = "1.33.0"
 detekt = "1.23.6"
@@ -123,4 +123,4 @@
 rxjava = "io.reactivex.rxjava3:rxjava:3.1.9"
 slackLints-checks = { module = "com.slack.lint:slack-lint-checks", version.ref = "slack-lint" }
 slackLints-annotations = { module = "com.slack.lint:slack-lint-annotations", version.ref = "slack-lint" }
-truth = "com.google.truth:truth:1.4.4"
\ No newline at end of file
+truth = "com.google.truth:truth:1.4.4"
```

**Comment by ZacSweers** [comment]
Ahhh! Thanks 🙇, sorry for the noise!

**Comment by rock3r** [comment]
No worries
