### ISSUE TITLE
SelectableLazyColumn will crash when removing list item

### ISSUE THREAD

**Issue by elonzh** [JetBrains/jewel#732]
### Reproduce

```kotlin
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import org.jetbrains.jewel.foundation.lazy.SelectableLazyColumn
import org.jetbrains.jewel.foundation.lazy.itemsIndexed
import org.jetbrains.jewel.intui.standalone.theme.IntUiTheme
import org.jetbrains.jewel.ui.component.DefaultButton
import org.jetbrains.jewel.ui.component.Text

@Composable
fun ItemRow(
    values: MutableList<String>,
    index: Int,
    v: String,
) {
    Row(Modifier.padding(8.dp)) {
        Text(v)
        Spacer(Modifier.weight(1f))
        DefaultButton({
            values.removeAt(index)
        }) {
            Text("Delete")
        }
    }
}

fun main() {
    application {
        Window(onCloseRequest = ::exitApplication) {
            val values =
                remember {
                    mutableStateListOf("A", "B", "C")
                }

            IntUiTheme {
                Row {
                    // Work as expected
                    // LazyColumn(Modifier.width(200.dp).border(1.dp, Color.Gray)) {
                    //    itemsIndexed(values) { index, v ->
                    //        ItemRow(values, index, v)
                    //    }
                    // }

                    // java.lang.IndexOutOfBoundsException: index: 2, size: 2
                    SelectableLazyColumn(Modifier.width(200.dp).border(1.dp, Color.Gray)) {
                        itemsIndexed(values) { index, v ->
                            ItemRow(values, index, v)
                        }
                    }
                }
            }
        }
    }
}
```

### Log

```text
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: index: 2, size: 2
	at androidx.compose.runtime.external.kotlinx.collections.immutable.internal.ListImplementation.checkElementIndex$runtime(ListImplementation.kt:15)
	at androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.get(SmallPersistentVector.kt:146)
	at androidx.compose.runtime.snapshots.SnapshotStateList.get(SnapshotStateList.kt:101)
	at org.jetbrains.jewel.foundation.lazy.SelectableLazyListScopeKt$itemsIndexed$4.invoke(SelectableLazyListScope.kt:180)
	at org.jetbrains.jewel.foundation.lazy.SelectableLazyListScopeKt$itemsIndexed$4.invoke(SelectableLazyListScope.kt:178)
	at org.jetbrains.jewel.foundation.lazy.SelectableLazyColumnKt$appendEntry$2.invoke(SelectableLazyColumn.kt:166)
	at org.jetbrains.jewel.foundation.lazy.SelectableLazyColumnKt$appendEntry$2.invoke(SelectableLazyColumn.kt:166)
	at androidx.compose.foundation.lazy.layout.NearestRangeKeyIndexMap$2$1.invoke(LazyLayoutKeyIndexMap.kt:89)
	at androidx.compose.foundation.lazy.layout.NearestRangeKeyIndexMap$2$1.invoke(LazyLayoutKeyIndexMap.kt:80)
	at androidx.compose.foundation.lazy.layout.MutableIntervalList.forEach(IntervalList.kt:159)
	at androidx.compose.foundation.lazy.layout.NearestRangeKeyIndexMap.<init>(LazyLayoutKeyIndexMap.kt:80)
	at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProviderLambda$1$itemProviderState$1.invoke(LazyListItemProvider.kt:53)
	at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProviderLambda$1$itemProviderState$1.invoke(LazyListItemProvider.kt:51)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2442)
	at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:201)
	at androidx.compose.runtime.DerivedSnapshotState.getCurrentRecord(DerivedState.kt:280)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.recordInvalidation(SnapshotStateObserver.kt:600)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.drainChanges(SnapshotStateObserver.kt:72)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.access$drainChanges(SnapshotStateObserver.kt:44)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:51)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:49)
	at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1946)
	at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1961)
	at androidx.compose.runtime.snapshots.SnapshotKt.access$advanceGlobalSnapshot(Snapshot.kt:1)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.sendApplyNotifications(Snapshot.kt:693)
	at androidx.compose.ui.node.SnapshotInvalidationTracker.sendAndPerformSnapshotChanges(SnapshotInvalidationTracker.skiko.kt:82)
	at androidx.compose.ui.scene.BaseComposeScene.sendPointerEvent-BGSDPeU(BaseComposeScene.skiko.kt:355)
	at androidx.compose.ui.scene.ComposeScene.sendPointerEvent-BGSDPeU$default(ComposeScene.skiko.kt:194)
	at androidx.compose.ui.scene.ComposeSceneMediator_desktopKt.onMouseEvent-d-4ec7I(ComposeSceneMediator.desktop.kt:802)
	at androidx.compose.ui.scene.ComposeSceneMediator_desktopKt.access$onMouseEvent-d-4ec7I(ComposeSceneMediator.desktop.kt:1)
	at androidx.compose.ui.scene.ComposeSceneMediator.onMouseEvent(ComposeSceneMediator.desktop.kt:435)
	at androidx.compose.ui.scene.ComposeSceneMediator.access$onMouseEvent(ComposeSceneMediator.desktop.kt:113)
	at androidx.compose.ui.scene.ComposeSceneMediator$mouseListener$1.mouseReleased(ComposeSceneMediator.desktop.kt:258)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6668)
	at java.desktop/java.awt.Component.processEvent(Component.java:6433)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5038)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4866)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by hamen** [comment]
Hi @elonzh. Thank you for bringing this to our attention.

We looked into it, and, unfortunately, the current implementation of `SelectableLazyColumn` is not equipped to work with `MutableList`s.
Although we plan to reiterate and expand on it in 2025, for the moment, we suggest you to use it with an `List`, as in our [example](https://github.com/JetBrains/jewel/blob/f5dae4836a2218597d34fa4038588bfe151de2c7/samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt#L69).

Thank you for your patience.
